#!/bin/sh

dbus-daemon \
  --fork \
  --print-pid --print-address \
  --address=unix:path=$HOME/agile_bus_socket \
  --config-file=dbus/agile.conf

docker run \
  -d \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
  --security-opt apparmor:unconfined \
  -p 8080:8080/tcp \
  -v $HOME/agile_bus_socket:/usr/src/app/agile_bus_socket \
  -e DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/agile_bus_socket \
  $1
